################################# PrivX 3.0 #################################

[3.0.host-store]
host-store.keyvault_id = "keyvault_id"
host-store.keyvault_secret = "keyvault_secret"

[3.0.role-store]
role-store.keyvault_id = "keyvault_id"
role-store.keyvault_secret = "keyvault_secret"

[3.0.user-store]
user-store.keyvault_id = "keyvault_id"
user-store.keyvault_secret = "keyvault_secret"

[3.0.workflow-engine]
workflow-engine.keyvault_id = "keyvault_id"
workflow-engine.keyvault_secret = "keyvault_secret"

################################# PrivX 18.0 #################################

[18.0.connection-manager]
connection-manager.keyvault_id = "keyvault_id"
connection-manager.keyvault_secret = "keyvault_secret"

[18.0.rdp-proxy]
rdp_proxy.keyvault_id = "keyvault_id"
rdp_proxy.keyvault_secret = "keyvault_secret"

[18.0.ssh-proxy]
ssh_proxy.keyvault_id = "keyvault_id"
ssh_proxy.keyvault_secret = "keyvault_secret"

[18.0.ssh-mitm]
ssh_mitm.keyvault_id = "keyvault_id"
ssh_mitm.keyvault_secret = "keyvault_secret"

[18.0.rdp-mitm]
rdp_mitm.keyvault_id = "keyvault_id"
rdp_mitm.keyvault_secret = "keyvault_secret"
