migration:
  enabled: true
  from: 26
  to: 27

  configs:
    new:
      name: new
      hook: pre-upgrade
      weight: "-5"
      files: "migrations/27/configs/new/*"
    common:
      name: common
      hook: pre-upgrade
      weight: "-5"
      files: "migrations/27/configs/common/*"
    syslog:
      name: syslog
      hook: pre-upgrade
      weight: "-5"
      files: "migrations/27/configs/syslog/*"
    nginx:
      name: nginx
      hook: pre-upgrade
      weight: "-5"
      files: "migrations/27/configs/nginx/*"
# ==========Upgrader===============
jobs:
  upgrader:
    name: upgrader
    hook: pre-upgrade
    weight: "-4"
    hookDeletePolicy: before-hook-creation
    image:
      repository: public.ecr.aws/sshprivx/upgrader
      pullPolicy: IfNotPresent
      tag: "27.1"
    imagePullSecrets:
      - name: docker-pull-secret
    environment:
      - name: UPGRADER_CMD
        value: upgrade
    useGlobalPodSecurityContext: true
    securityContext: {}
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    volumes:
      enabled: true
      volumeMounts:
        - mountPath: /opt/privx/keyvault
          name: privx-config
          subPath: keyvault
        - mountPath: /opt/privx/etc
          name: privx-config
          subPath: privxetc
        - mountPath: /etc/nginx/ssl
          name: privx-config
          subPath: nginxssl
      claims:
        - name: privx-config
          claimName: privx-claim
      configMaps:
        - name: privx-new-config
          configMap:
            name: new-config
        - name: privx-common-config
          configMap:
            name: common-config
        - name: privx-nginx-config
          configMap:
            name: nginx-config
    initContainers:
      - name: config-copier
        image: k8s.gcr.io/busybox
        command: [ "/bin/sh", "-c" ]
        args:
          - mkdir -p /opt/privx/etc/new;
            echo copying new template tomls;
            cp -f /new-templates-mount/* /opt/privx/etc/new/;
            echo copying common configs;
            cp -f /common-config-mount/* /opt/privx/etc/;
            echo copying nginx configs;
            cp -f /upgraded-nginx-config/* /etc/nginx/privx/;
        volumeMounts:
          - name: privx-new-config
            mountPath: /new-templates-mount
          - name: privx-common-config
            mountPath: /common-config-mount
          - name: privx-config
            mountPath: /opt/privx/etc
            subPath: privxetc
          - name: privx-nginx-config
            mountPath: /upgraded-nginx-config
          - name: privx-config
            mountPath: /etc/nginx/privx
            subPath: nginxprivx
        resources: {}
          # limits:
          #   cpu: 100m
          #   memory: 128Mi
          # requests:
          #   cpu: 100m
          #   memory: 128Mi
    serviceAccount:
      create: false
      annotations: {}
      name: upgrader
    rbac:
      create: false
