################################# PrivX 3.0 #################################

[3.0.hoststore]
hoststore.keyvault_id = "keyvault_id"
hoststore.keyvault_secret = "keyvault_secret"

[3.0.rolestore]
rolestore.keyvault_id = "keyvault_id"
rolestore.keyvault_secret = "keyvault_secret"

[3.0.user-store]
userstore.keyvault_id = "keyvault_id"
userstore.keyvault_secret = "keyvault_secret"

[3.0.workflowengine]
workflowengine.keyvault_id = "keyvault_id"
workflowengine.keyvault_secret = "keyvault_secret"

################################# PrivX 18.0 #################################

[18.0.connectionmanager]
connectionmanager.keyvault_id = "keyvault_id"
connectionmanager.keyvault_secret = "keyvault_secret"

[18.0.rdp-proxy]
rdp_proxy.keyvault_id = "keyvault_id"
rdp_proxy.keyvault_secret = "keyvault_secret"

[18.0.ssh-proxy]
ssh_proxy.keyvault_id = "keyvault_id"
ssh_proxy.keyvault_secret = "keyvault_secret"

[18.0.ssh-mitm]
ssh_mitm.keyvault_id = "keyvault_id"
ssh_mitm.keyvault_secret = "keyvault_secret"

[18.0.rdp-mitm]
rdp_mitm.keyvault_id = "keyvault_id"
rdp_mitm.keyvault_secret = "keyvault_secret"
