{{- include "check.kubeVersion" . }}
{{- if .Values.cert.selfsigned }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ default "selfsigned" .Values.cert.clusterIssuerName }}
spec:
  selfSigned: {}
{{- end }}
