{{- $globalContext := . }}
{{- range $config := .Values.configs}}
{{- $files := $config.files -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name }}-config
  annotations:
    "helm.sh/hook": "{{ $config.hook }}"
    "helm.sh/hook-weight": "{{ $config.weight }}"
data:
{{ range $path, $d :=  $globalContext.Files.Glob  $files }}
  {{ base ($path | toString) }}: |+
  {{- tpl ($d | toString | nindent 4) $globalContext }}
{{ end }}
---
{{- end }}
