{{- $globalContext := . }}
{{- range $service := .Values.ms}}
{{- range $ingress := $service.ingress}}
{{- $svcPort := $service.service.port -}}
{{- if and $ingress.className (not (semverCompare ">=1.18-0" $globalContext.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey $ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $ingress.annotations "kubernetes.io/ingress.class" $ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $globalContext.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $globalContext.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "privx.fullname" $globalContext }}-{{ $service.name }}-{{ $ingress.name }}
  labels:
    app.kubernetes.io/name: {{ include "privx.name" $globalContext }}-{{ $service.name }}-{{ $ingress.name }}
  {{- if or $ingress.useCommonAnnotations $ingress.annotations }}
  annotations:
    {{- if $ingress.useCommonAnnotations }}
      {{- with $globalContext.Values.ingress.common.annotations }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
    {{- with $ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end}}
spec:
  {{- if and (or $ingress.className $globalContext.Values.ingress.common.className) (semverCompare ">=1.18-0" $globalContext.Capabilities.KubeVersion.GitVersion) }}
    {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className }}
    {{- else }}
  ingressClassName: {{ $globalContext.Values.ingress.common.className }}
    {{- end }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- if $ingress.useCommonHost }}
        - {{ $globalContext.Values.ingress.common.host | quote }}
        {{- else }}
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    {{- if $ingress.useCommonHost }}
    - host: {{ $globalContext.Values.ingress.common.host | quote }}
    {{- else }}
    - host: {{ .host | quote }}
    {{- end}}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $globalContext.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $globalContext.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $service.name }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $service.name }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
