{{- $globalContext := . }}
{{- range $job := .Values.jobs}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "privx.fullname" $globalContext }}-{{ $job.name }}
  annotations:
    "helm.sh/hook": "{{ $job.hook }}"
    "helm.sh/hook-weight": "{{ $job.weight }}"
    "helm.sh/hook-delete-policy": "{{ $job.hookDeletePolicy }}"
spec:
  template:
    spec:
      {{- with $job.initContainers }}
      initContainers:
        {{- range $initContainer := $job.initContainers }}
          {{- if $job.useGlobalPodSecurityContext }}
        - securityContext:
            {{- toYaml $globalContext.Values.securityContext | nindent 12 }}
          {{- else }}
        - securityContext: {}
          {{- end }}
          {{- with $initContainer }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if not $initContainer.image }}
          image: "{{ $globalContext.Values.privxRepository | default "public.ecr.aws/sshprivx" }}/{{ $initContainer.name }}:{{ $globalContext.Values.privxVersion | default "latest" }}"
          {{- end }}
          {{- $containerName := $initContainer.name }}
          {{- range $icEnv := $job.initContainersEnvironment }}
            {{- if eq $icEnv.name $containerName}}
          env:
                {{- range $env := $icEnv.env}}
            - name: {{ $env.name }}
                  {{- if $env.valueFromTemplate }}
              value: {{ tpl $env.valueFromTemplate $globalContext | toString }}
                  {{- else }}
              value: {{ $env.value }}
                  {{- end}}
                {{- end}}
            {{- end}}
          {{- end}}
        {{- end }}
      {{- end }}
      {{- if $job.serviceAccount.create }}
      serviceAccountName: {{ $job.serviceAccount.name }}
      {{- end }}
      securityContext:
        {{- if $job.useGlobalPodSecurityContext }}
          {{- toYaml $globalContext.Values.podSecurityContext | nindent 8 }}
        {{- else }}
          {{- toYaml $job.podSecurityContext | nindent 8 }}
        {{- end }}
      {{- with $job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $globalContext.Chart.Name }}-{{ $job.name }}
          securityContext:
            {{- if $job.useGlobalPodSecurityContext }}
              {{- toYaml $globalContext.Values.securityContext | nindent 12 }}
            {{- else }}
              {{- toYaml $job.securityContext | nindent 12 }}
            {{- end }}
          image: "{{ $job.image.repository | default "public.ecr.aws/sshprivx" }}/{{ $job.image.name }}:{{ $job.image.tag | default "latest" }}"
          imagePullPolicy: {{ $job.image.pullPolicy }}
          {{- with $job.environment }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $job.useGlobalPodSecurityContext }}
            {{- range $env := $job.environment }}
              {{- if eq $env.name "PRIVX_USER" }}
            - name: "{{ $env.name }}"
              value: "{{ $globalContext.Values.podSecurityContext.runAsUser | toString }}"
              {{- end }}
              {{- if eq $env.name "PRIVX_GROUP" }}
            - name: "{{ $env.name }}"
              value: "{{ $globalContext.Values.podSecurityContext.fsGroup | toString }}"
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with $job.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $job.volumes.enabled }}
          volumeMounts:
            {{- range $job.volumes.volumeMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
              subPath: {{ .subPath }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml $job.resources | nindent 12 }}
      restartPolicy: Never
      {{- if $job.volumes.enabled }}
      volumes:
        {{- range $job.volumes.claims }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}
        {{- range $job.volumes.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
        {{- range $job.volumes.configMaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap.name }}
            {{- with .configMap.items }}
            items:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        {{- end }}
      {{- end }}
---
{{- end }}
