
{{- $globalContext := . }}
{{- range $service := .Values.ms}}
{{- if $service.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "privx.name" $globalContext }}-{{ $service.name }}
  {{- with $service.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- range $job := .Values.jobs }}
{{- if $job.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $job.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "privx.name" $globalContext }}-{{ $job.name }}
  {{- with $job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
