{{- $globalContext := . }}
{{- range $service := .Values.ms}}
{{- if and (eq $service.name "syslog-service") (not ($globalContext.Values.privx.syslog.enabled)) }}
{{- else }}
{{- if $service.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  labels:
    app.kubernetes.io/name: {{ include "privx.name" $globalContext }}-{{ $service.name }}
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range $service.service.internal }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "privx.name" $globalContext }}-{{ $service.name }}
---
{{- end }}
{{- end }}
{{- end }}
