migration:
  enabled: true
  from: 20
  to: 21

  configs:
    new:
      name: new
      hook: pre-upgrade
      weight: "-5"
      files: "migrations/21/configs/new/*"
    version:
      name: version
      hook: pre-upgrade
      weight: "-5"
      files: "migrations/21/configs/version/*"
# ==========Upgrader===============
jobs:
  upgrader:
    name: upgrader
    hook: pre-upgrade
    weight: "-4"
    hookDeletePolicy: before-hook-creation
    image:
      repository: public.ecr.aws/sshprivx/upgrader
      pullPolicy: IfNotPresent
      tag: "21.3"
    imagePullSecrets:
      - name: docker-pull-secret
    environment:
      - name: UPGRADER_CMD
        value: upgrade
    podSecurityContext:
      fsGroup: 5111
      runAsUser: 5111
    securityContext: {}
    volumes:
      enabled: true
      volumeMounts:
        - mountPath: /opt/privx/keyvault
          name: privx-config
          subPath: keyvault
        - mountPath: /opt/privx/etc
          name: privx-config
          subPath: privxetc
        - mountPath: /etc/nginx/ssl
          name: privx-config
          subPath: nginxssl
      claims:
        - name: privx-config
          claimName: privx-claim
      configMaps:
        - name: privx-new-config
          configMap:
            name: new-config
        - name: privx-version-config
          configMap:
            name: version-config
    initContainers:
      - name: config-copier
        image: k8s.gcr.io/busybox
        command: [ "/bin/sh", "-c" ]
        args:
          - mkdir -p /opt/privx/etc/new;
            echo copying new template tomls;
            cp -f /new-templates-mount/* /opt/privx/etc/new/;
            echo copying version configs;
            cp -f /version-config-mount/* /opt/privx/etc/;
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 5111
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: privx-new-config
            mountPath: /new-templates-mount
          - name: privx-version-config
            mountPath: /version-config-mount
          - name: privx-config
            mountPath: /opt/privx/etc
            subPath: privxetc
    serviceAccount:
      create: false
      annotations: {}
      name: upgrader
    rbac:
      create: false
